O3-2820 Refactor the billing extension on start visit form
openmrs/openmrs-esm-billing-app pull request #5
Opened 2024-02-07 19:42 UTC by ODORA0

## Requirements
- [ ] This PR has a title that briefly describes the work done including a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) type prefix and a Jira ticket number if applicable. See existing PR titles for inspiration.

#### For changes to apps
- [ ]  My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).

#### If applicable
At the moment all the attributes of this extension are specific for the KenyaEMR use case, this PR refactors the start visit form and adds configurations for hardcoded values
## Summary

## Screenshots

## Related Issue

## Other

2024-02-09 09:04 UTC, pirupius requested changes

2024-02-09 09:04 UTC, pirupius commented on src/billing-form/billing-checkin-form.component.tsx
> -  const shouldBillPatient =
Please update the PR description and add any relevant screenshots or recording. I see you deleted `shouldBillPatient`

2024-02-09 09:20 UTC, ODORA0 commented on src/billing-form/billing-checkin-form.component.tsx
> -  const shouldBillPatient =
I had to remove the hardcoded shouldBillPatient logic in billing checkin form based on the visit attributes component

2024-02-09 09:37 UTC, CynthiaKamau commented on src/config-schema.ts
> +      paymentDetails: 'caf2124f-00a9-4620-a250-efd8535afd6d',
perhaps we could separate the concepts from custom uuids from the visit attributes to make it easier to do the configuration

2024-02-09 10:27 UTC, ODORA0 commented on src/config-schema.ts
> +      paymentDetails: 'caf2124f-00a9-4620-a250-efd8535afd6d',
@CynthiaKamau Done

2024-02-12 06:29 UTC, CynthiaKamau approved these changes
LGTM

2024-02-12 14:21 UTC, pirupius requested changes

2024-02-12 14:21 UTC, pirupius commented on src/billing-form/billing-checkin-form.component.tsx
> +  const { patientCatergory, catergoryConcepts } = useConfig();
It looks like you have a typo on the word `category` and it affects other files as well.

2024-02-13 05:58 UTC, pirupius approved these changes
Will clean this up in a follow PR

2024-02-13 05:58 UTC, merged